"""Hub-owned SQLite store. The ONLY place user progress lives — never the sidecars."""

from .db import (
    add_brief_note,
    add_custom_topic,
    brief_habit_weeks,
    connect,
    course_flashcard_states,
    course_quiz_progress,
    delete_brief_note,
    get_course_assessments,
    get_course_progress,
    get_custom_topic,
    get_episode_progress,
    init_db,
    list_brief_notes,
    list_custom_topics,
    list_reflections,
    record_attempt,
    record_brief_visit,
    record_flashcard_review,
    save_reflection,
    set_course_assessment,
    set_episode_listened,
    set_lesson_completed,
    update_custom_topic,
)

__all__ = [
    "connect",
    "init_db",
    "get_episode_progress",
    "set_episode_listened",
    "save_reflection",
    "list_reflections",
    "record_attempt",
    "record_brief_visit",
    "brief_habit_weeks",
    "add_brief_note",
    "list_brief_notes",
    "delete_brief_note",
    "add_custom_topic",
    "list_custom_topics",
    "get_custom_topic",
    "update_custom_topic",
    "get_course_progress",
    "set_lesson_completed",
    "course_quiz_progress",
    "course_flashcard_states",
    "record_flashcard_review",
    "get_course_assessments",
    "set_course_assessment",
]
